"""empty message

Revision ID: 237d14aabc0a
Revises: 
Create Date: 2023-10-31 23:34:59.937097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237d14aabc0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('num_circles', sa.Integer(), nullable=False),
    sa.Column('num_reps', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_data')
    # ### end Alembic commands ###
